# Generated by Django 5.2.1 on 2025-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0003_userprofile_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logos/'),
        ),
    ]
