# Generated by Django 5.2.1 on 2025-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0004_userprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='Array of interests: football, basketball, hockey, baseball, soccer, custom'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('team', 'Team'), ('organization', 'Organization'), ('enterprise', 'Enterprise')], max_length=50, null=True),
        ),
    ]
