from django.urls import path
from .views import (
    WebsiteSettingsView, 
    NavigationMenuView, 
    UpdateNavigationMenuItemView,
    BannerListCreateView,
    BannerRetrieveUpdateDestroyView,
    BlogListCreateView,
    BlogRetrieveUpdateDestroyView,
    TestimonialListCreateView,
    TestimonialRetrieveUpdateDestroyView,
    ProductListCreateView,
    ProductRetrieveUpdateDestroyView,
    CategoryListCreateView,
    CategoryRetrieveUpdateDestroyView,
    InventoryStatsAPIView,
    PaymentSettingsView,
    ShippingMethodListCreateView,
    ShippingMethodRetrieveUpdateDestroyView,
    ShippingMethodToggleStatusView,
    TaxConfigurationView,
    GeneralSettingsView,
    GeneralSettingsResetView,
    NotificationListCreateView,
    NotificationRetrieveUpdateDestroyView,
    NotificationMarkAsReadView,
    NotificationMarkAllAsReadView,
    NotificationDeleteAllView,
    NotificationSettingsView,
    ArtworkRequestListCreateView,
    ArtworkRequestRetrieveUpdateDestroyView,
    MembershipRequestListCreateView,
    MembershipRequestRetrieveUpdateDestroyView,
    MediaLibraryListCreateView,
    MediaLibraryRetrieveUpdateDestroyView
)

urlpatterns = [
    path('website-settings/', WebsiteSettingsView.as_view()),
    path('navigation-menu/', NavigationMenuView.as_view()),
    path('navigation-menu/update/', UpdateNavigationMenuItemView.as_view()),
    path('banners/', BannerListCreateView.as_view()),
    path('banners/<int:id>/', BannerRetrieveUpdateDestroyView.as_view()),
    path('blogs/', BlogListCreateView.as_view()),
    path('blogs/<int:id>/', BlogRetrieveUpdateDestroyView.as_view()),
    path('testimonials/', TestimonialListCreateView.as_view()),
    path('testimonials/<int:id>/', TestimonialRetrieveUpdateDestroyView.as_view()),
    path('products/', ProductListCreateView.as_view()),
    path('products/<int:id>/', ProductRetrieveUpdateDestroyView.as_view()),
    path('categories/', CategoryListCreateView.as_view()),
    path('categories/<int:id>/', CategoryRetrieveUpdateDestroyView.as_view()),
    path('inventory/stats/', InventoryStatsAPIView.as_view()),
    path('settings/payment/', PaymentSettingsView.as_view()),
    path('settings/tax/', TaxConfigurationView.as_view()),
    path('settings/general/', GeneralSettingsView.as_view()),
    path('settings/general/reset/', GeneralSettingsResetView.as_view()),
    path('settings/notifications/', NotificationSettingsView.as_view()),
    path('notifications/', NotificationListCreateView.as_view()),
    path('notifications/<int:id>/', NotificationRetrieveUpdateDestroyView.as_view()),
    path('notifications/<int:id>/mark-read/', NotificationMarkAsReadView.as_view()),
    path('notifications/mark-all-read/', NotificationMarkAllAsReadView.as_view()),
    path('notifications/delete-all/', NotificationDeleteAllView.as_view()),
    path('shipping-methods/', ShippingMethodListCreateView.as_view()),
    path('shipping-methods/<int:id>/', ShippingMethodRetrieveUpdateDestroyView.as_view()),
    path('shipping-methods/<int:id>/toggle-status/', ShippingMethodToggleStatusView.as_view()),
    path('artwork-requests/', ArtworkRequestListCreateView.as_view()),
    path('artwork-requests/<int:id>/', ArtworkRequestRetrieveUpdateDestroyView.as_view()),
    path('membership-requests/', MembershipRequestListCreateView.as_view()),
    path('membership-requests/<int:id>/', MembershipRequestRetrieveUpdateDestroyView.as_view()),
    path('media-library/', MediaLibraryListCreateView.as_view()),
    path('media-library/<int:id>/', MediaLibraryRetrieveUpdateDestroyView.as_view()),
]

