# Generated by Django 5.2.1 on 2025-06-04 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usershirts_shirt', to='product_management_app.shirt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usershirts_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
