# Generated by Django 5.2.1 on 2025-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0003_favoriteshirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='back_base',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='back_child1',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='back_child2',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='back_child3',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='front_base',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='front_child1',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='front_child2',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='front_child3',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='left_base',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='left_child1',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='left_child2',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='left_child3',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='right_base',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='right_child1',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='right_child2',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='right_child3',
            field=models.FileField(blank=True, null=True, upload_to='shirts/Shirt_images/'),
        ),
    ]
