# Generated by Django 5.2.1 on 2025-08-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0004_shirt_back_base_shirt_back_child1_shirt_back_child2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shirt',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirts_subcategory', to='product_management_app.shirtsubcategory'),
        ),
    ]
