# Generated by Django 5.2.1 on 2025-11-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0005_shirtsubcategory_shirt_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('jerseys', 'Jerseys'), ('shorts', 'Shorts'), ('hoodies', 'Hoodies'), ('pants', 'Pants'), ('jacket', 'Jacket')], max_length=50)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('hockey', 'Hockey'), ('baseball', 'Baseball'), ('soccer', 'Soccer')], max_length=50)),
                ('category', models.CharField(choices=[('jerseys', 'Jerseys'), ('shorts', 'Shorts'), ('hoodies', 'Hoodies'), ('pants', 'Pants'), ('jacket', 'Jacket'), ('accessories', 'Accessories')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('front_black_layer', models.ImageField(blank=True, null=True, upload_to='customizer/front/')),
                ('front_white_layer', models.ImageField(blank=True, null=True, upload_to='customizer/front/')),
                ('front_svg_layer', models.FileField(blank=True, null=True, upload_to='customizer/front/')),
                ('back_black_layer', models.ImageField(blank=True, null=True, upload_to='customizer/back/')),
                ('back_white_layer', models.ImageField(blank=True, null=True, upload_to='customizer/back/')),
                ('back_svg_layer', models.FileField(blank=True, null=True, upload_to='customizer/back/')),
                ('left_black_layer', models.ImageField(blank=True, null=True, upload_to='customizer/left/')),
                ('left_white_layer', models.ImageField(blank=True, null=True, upload_to='customizer/left/')),
                ('left_svg_layer', models.FileField(blank=True, null=True, upload_to='customizer/left/')),
                ('right_black_layer', models.ImageField(blank=True, null=True, upload_to='customizer/right/')),
                ('right_white_layer', models.ImageField(blank=True, null=True, upload_to='customizer/right/')),
                ('right_svg_layer', models.FileField(blank=True, null=True, upload_to='customizer/right/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customizer',
                'verbose_name_plural': 'Customizers',
                'ordering': ['-created_at'],
            },
        ),
    ]
