# Generated by Django 5.2.1 on 2025-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0006_customizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('geometric', 'Geometric'), ('organic', 'Organic'), ('texture', 'Texture'), ('abstract', 'Abstract'), ('sports', 'Sports'), ('military', 'Military')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('pattern_image', models.ImageField(blank=True, null=True, upload_to='patterns/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'ordering': ['-created_at'],
            },
        ),
    ]
