# Generated by Django 5.2.1 on 2025-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0007_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
                ('color_code', models.CharField(help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('category', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent'), ('neutral', 'Neutral'), ('team_colors', 'Team Colors'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['-created_at'],
            },
        ),
    ]
