# Generated by Django 5.2.1 on 2025-11-05 16:44

import product_management_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0008_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=255)),
                ('font_family', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-Serif'), ('display', 'Display'), ('script', 'Script'), ('monospace', 'Monospace')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('font_file', models.FileField(blank=True, null=True, upload_to='fonts/', validators=[product_management_app.models.validate_font_file])),
                ('preview_text', models.CharField(blank=True, help_text='Preview text to display the font', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Font',
                'verbose_name_plural': 'Fonts',
                'ordering': ['-created_at'],
            },
        ),
    ]
