# Generated by Django 5.2.1 on 2025-11-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0009_font'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the model is active'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='views',
            field=models.IntegerField(default=0, help_text='Total number of views'),
        ),
        migrations.CreateModel(
            name='UserCustomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_data', models.JSONField(blank=True, default=dict, help_text='JSON data storing customization details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomizers_customizer', to='product_management_app.customizer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercustomizers_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Customizer',
                'verbose_name_plural': 'User Customizers',
                'ordering': ['-created_at'],
            },
        ),
    ]
