# Generated by Django 5.2.1 on 2025-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0012_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report_date', models.DateField(auto_now_add=True, help_text='Date when report was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Analysis Report',
                'verbose_name_plural': 'Customer Analysis Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='GrowthTrendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_growth', models.DecimalField(decimal_places=2, default=0, help_text='Monthly growth percentage', max_digits=5)),
                ('yearly_growth', models.DecimalField(decimal_places=2, default=0, help_text='Yearly growth percentage', max_digits=5)),
                ('quarterly_growth', models.DecimalField(decimal_places=2, default=0, help_text='Quarterly growth percentage', max_digits=5)),
                ('market_share', models.DecimalField(decimal_places=2, default=0, help_text='Market share percentage', max_digits=5)),
                ('report_date', models.DateField(auto_now_add=True, help_text='Date when report was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Growth Trend Report',
                'verbose_name_plural': 'Growth Trend Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('top_product_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('top_product_units_sold', models.IntegerField(default=0)),
                ('top_category', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateField(auto_now_add=True, help_text='Date when report was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Sales Report',
                'verbose_name_plural': 'Product Sales Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_month_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_month_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('growth_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Growth percentage like +20% or -5%', max_digits=5)),
                ('total_orders', models.IntegerField(default=0)),
                ('report_date', models.DateField(auto_now_add=True, help_text='Date when report was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenue Report',
                'verbose_name_plural': 'Revenue Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
