# Generated by Django 4.2.27 on 2025-12-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0018_artworkrequest_additional_details_and_more'),
        ('product_management_app', '0013_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='back_base',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='back_child1',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='back_child2',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='back_child3',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='black_base_file',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='front_base',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='front_child1',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='front_child2',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='front_child3',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='left_base',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='left_child1',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='left_child2',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='left_child3',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='right_base',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='right_child1',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='right_child2',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='right_child3',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='svg_file',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='white_base_file',
        ),
        migrations.AddField(
            model_name='shirt',
            name='black_back',
            field=models.ImageField(blank=True, help_text='Black back image', null=True, upload_to='shirts/black/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='black_front',
            field=models.ImageField(blank=True, help_text='Black front image', null=True, upload_to='shirts/black/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='black_left',
            field=models.ImageField(blank=True, help_text='Black left image', null=True, upload_to='shirts/black/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='black_right',
            field=models.ImageField(blank=True, help_text='Black right image', null=True, upload_to='shirts/black/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the shirt', null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the shirt', max_digits=10),
        ),
        migrations.AddField(
            model_name='shirt',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='svg_back',
            field=models.FileField(blank=True, help_text='SVG back file (optional)', null=True, upload_to='shirts/svg/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='svg_front',
            field=models.FileField(blank=True, help_text='SVG front file (optional)', null=True, upload_to='shirts/svg/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='svg_left',
            field=models.FileField(blank=True, help_text='SVG left file (optional)', null=True, upload_to='shirts/svg/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='svg_right',
            field=models.FileField(blank=True, help_text='SVG right file (optional)', null=True, upload_to='shirts/svg/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='white_back',
            field=models.ImageField(blank=True, help_text='White back image', null=True, upload_to='shirts/white/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='white_front',
            field=models.ImageField(blank=True, help_text='White front image', null=True, upload_to='shirts/white/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='white_left',
            field=models.ImageField(blank=True, help_text='White left image', null=True, upload_to='shirts/white/'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='white_right',
            field=models.ImageField(blank=True, help_text='White right image', null=True, upload_to='shirts/white/'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirts_category', to='website_management_app.category'),
        ),
        migrations.CreateModel(
            name='ShirtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional shirt image', upload_to='shirts/other_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='product_management_app.shirt')),
            ],
            options={
                'verbose_name': 'Shirt Image',
                'verbose_name_plural': 'Shirt Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShirtDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('colors', models.JSONField(default=dict, help_text='Colors for front, back, left, right (5 each)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shirt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='product_management_app.shirt')),
            ],
        ),
    ]
