# Generated by Django 4.2.27 on 2025-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0014_remove_shirt_back_base_remove_shirt_back_child1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirtdraft',
            name='colors',
        ),
        migrations.AddField(
            model_name='shirtdraft',
            name='svg_part_colors',
            field=models.JSONField(blank=True, default=dict, help_text="Flat map of svg part colors, keys like 'front_0'"),
        ),
    ]
