# Generated by Django 4.2.27 on 2025-12-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0015_remove_shirtdraft_colors_shirtdraft_svg_part_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='pattern_image',
            field=models.FileField(blank=True, null=True, upload_to='patterns/'),
        ),
    ]
