# Generated by Django 4.2.27 on 2026-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0016_alter_pattern_pattern_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Optional sub-category for customizer', max_length=255, null=True),
        ),
    ]
