# Generated by Django 4.2.27 on 2026-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0017_customizer_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizer',
            name='sub_category',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of sub-categories for customizer', null=True),
        ),
    ]
