# Generated by Django 4.2.27 on 2026-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0024_update_shirt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='size',
            field=models.TextField(blank=True, help_text='Size of the shirt', null=True),
        ),
    ]
