# Generated by Django 4.2.27 on 2026-01-08 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0035_change_customizer_category_to_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='patterns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_images', to='product_management_app.pattern')),
            ],
            options={
                'verbose_name': 'Pattern Image',
                'verbose_name_plural': 'Pattern Images',
            },
        ),
    ]
