# Generated by Django 5.2.1 on 2025-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='ProSix', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#000000', help_text='Primary color hex code', max_length=7)),
                ('accent_color', models.CharField(default='#FFFFFF', help_text='Accent color hex code', max_length=7)),
                ('navigation_menu', models.JSONField(blank=True, default=list, help_text='Array of navigation menu items with name and link')),
                ('website_description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('seo_keywords', models.TextField(blank=True, help_text='SEO keywords (comma-separated)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
