# Generated by Django 5.2.1 on 2025-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_image_url', models.URLField(max_length=500)),
                ('position', models.CharField(choices=[('hero_section', 'Hero Section'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('popup', 'Popup')], max_length=50)),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
