# Generated by Django 5.2.1 on 2025-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(help_text='Short summary or description')),
                ('content', models.TextField()),
                ('featured_image_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('category', models.CharField(choices=[('news', 'News'), ('update', 'Update'), ('tips', 'Tips'), ('events', 'Events')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
