# Generated by Django 5.2.1 on 2025-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='featured_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website_settings/'),
        ),
    ]
