# Generated by Django 5.2.1 on 2025-11-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0007_remove_banner_banner_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_enabled', models.BooleanField(default=False, help_text='Enable/disable PayPal payment method')),
                ('stripe_enabled', models.BooleanField(default=False, help_text='Enable/disable Stripe payment method')),
                ('cash_app_enabled', models.BooleanField(default=False, help_text='Enable/disable Cash App payment method')),
                ('zelle_enabled', models.BooleanField(default=False, help_text='Enable/disable Zelle payment method')),
                ('default_currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar')], default='USD', help_text='Default currency for payments', max_length=3)),
                ('stripe_api_key', models.CharField(blank=True, help_text='Stripe API key for payment processing', max_length=255, null=True)),
                ('stripe_webhook_secret', models.CharField(blank=True, help_text='Stripe webhook secret for verifying webhook events', max_length=255, null=True)),
                ('enable_3d_secure', models.BooleanField(default=False, help_text='Enable/disable 3D Secure authentication')),
                ('admin_email', models.EmailField(blank=True, help_text='Admin email address for payment notifications', max_length=254, null=True)),
                ('email_on_payment_success', models.BooleanField(default=False, help_text='Send email notification on successful payment')),
                ('email_on_payment_failure', models.BooleanField(default=False, help_text='Send email notification on failed payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
