# Generated by Django 5.2.1 on 2025-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0008_payment_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(help_text='Name of the shipping method', max_length=255)),
                ('provider', models.CharField(choices=[('DHL', 'DHL'), ('FedEx', 'FedEx'), ('UPS', 'UPS'), ('USPS', 'USPS'), ('Flat Rate', 'Flat Rate')], help_text='Shipping provider/service', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping cost', max_digits=10)),
                ('delivery_time', models.CharField(help_text="Estimated delivery time (e.g., '3-5 business days')", max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Status of the shipping method', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
