# Generated by Django 5.2.1 on 2025-11-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0009_shipping_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_tax_setting', models.BooleanField(default=False, help_text='Enable/disable tax settings')),
                ('tax_type', models.CharField(blank=True, choices=[('VAT', 'VAT (Value Added Tax)'), ('Sales Tax', 'Sales Tax'), ('GST', 'GST (Goods & Services Tax)')], help_text='Type of tax to apply', max_length=50, null=True)),
                ('tax_inclusive_pricing', models.BooleanField(default=False, help_text='Whether prices include tax or not')),
                ('business_name', models.CharField(blank=True, help_text='Business name', max_length=255, null=True)),
                ('tax_id_vat_number', models.CharField(blank=True, help_text='Tax ID or VAT Number', max_length=255, null=True)),
                ('business_address', models.TextField(blank=True, help_text='Business address', null=True)),
                ('b2b_tax_exemption', models.BooleanField(default=False, help_text='Enable/disable B2B tax exemption')),
                ('digital_product_tax', models.BooleanField(default=False, help_text='Enable/disable tax on digital products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configuration',
            },
        ),
    ]
