# Generated by Django 5.2.1 on 2025-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0010_tax_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='ProSix', help_text='Site title', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Site description', null=True)),
                ('default_language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German')], default='English', help_text='Default language for the website', max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar')], default='USD', help_text='Default currency', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable/disable maintenance mode')),
                ('enable_analytics', models.BooleanField(default=False, help_text='Enable/disable analytics')),
                ('enable_notifications', models.BooleanField(default=False, help_text='Enable/disable notifications')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=25, null=True)),
                ('business_address', models.TextField(blank=True, help_text='Business address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
    ]
