# Generated by Django 5.2.1 on 2025-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0011_general_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, help_text='Emoji for the notification', max_length=10, null=True)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('body', models.TextField(help_text='Notification body/content')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Notification date')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_order_notification', models.BooleanField(default=False, help_text='Enable/disable new order email notifications')),
                ('payment_notifications', models.BooleanField(default=False, help_text='Enable/disable payment email notifications')),
                ('low_stock_alerts', models.BooleanField(default=False, help_text='Enable/disable low stock email alerts')),
                ('customer_messages', models.BooleanField(default=False, help_text='Enable/disable customer message email notifications')),
                ('enable_push_notifications', models.BooleanField(default=False, help_text='Enable/disable push notifications')),
                ('new_order_alerts', models.BooleanField(default=False, help_text='Enable/disable new order push alerts')),
                ('system_alerts', models.BooleanField(default=False, help_text='Enable/disable system push alerts')),
                ('enable_sms_notification', models.BooleanField(default=False, help_text='Enable/disable SMS notifications')),
                ('admin_phone_number', models.CharField(blank=True, help_text='Admin phone number for SMS notifications', max_length=25, null=True)),
                ('critical_alerts', models.BooleanField(default=False, help_text='Enable/disable critical SMS alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
