# Generated by Django 5.2.1 on 2025-11-28 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0013_testimonial_image_testimonial_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the requester', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('instagram', models.CharField(blank=True, help_text='Instagram handle', max_length=255, null=True)),
                ('address', models.TextField(help_text='Full address')),
                ('organization_name', models.CharField(blank=True, help_text='Organization or team name', max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('coach', 'Coach'), ('parent', 'Parent'), ('player', 'Player')], help_text='Type of user: coach, parent, or player', max_length=20)),
                ('order_quantity', models.IntegerField(default=1, help_text='Order quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('team_color', models.CharField(help_text='Team color(s)', max_length=255)),
                ('need_home_away_mockup', models.BooleanField(default=False, help_text='Whether home/away mockup is needed')),
                ('team_attribute', models.CharField(choices=[('traditional', 'Traditional'), ('non-traditional', 'Non-Traditional'), ('combo', 'Combo')], help_text='Team attribute: traditional, non-traditional, or combo', max_length=50)),
                ('twill_type', models.CharField(choices=[('full_twill', 'Full Twill'), ('sub_twill', 'Sub-Twill'), ('silicone_twill', 'Silicone-Twill'), ('fully_sublimation', 'Fully-Sublimation'), ('dont_know', "Don't Know")], help_text='Type of twill needed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artwork Request',
                'verbose_name_plural': 'Artwork Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
