# Generated by Django 5.2.1 on 2025-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0014_artworkrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('mailing_address', models.TextField(help_text='Mailing address')),
                ('organization', models.CharField(help_text='Organization name', max_length=255)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('zip_code', models.CharField(help_text='ZIP code', max_length=20)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('user_type', models.CharField(choices=[('coach', 'Coach'), ('parent', 'Parent'), ('player', 'Player')], help_text='Type of user: coach, parent, or player', max_length=20)),
                ('twill_type', models.CharField(choices=[('youth', 'Youth'), ('semi_pro', 'Semi-Pro'), ('high_school', 'High School'), ('mock_up', 'Mock Up'), ('team_apparel', 'Team Apparel')], help_text='Are you in twill: youth, semi-pro, high school, mock up, or team apparel', max_length=50)),
                ('sport', models.CharField(blank=True, help_text='Sport name (optional)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Request',
                'verbose_name_plural': 'Membership Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
