# Generated by Django 5.2.1 on 2025-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0016_medialibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image', null=True, upload_to='banners/'),
        ),
    ]
