# Generated by Django 5.2.1 on 2025-12-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0017_remove_banner_banner_image_remove_banner_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkrequest',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Additional details or notes', null=True),
        ),
        migrations.AddField(
            model_name='artworkrequest',
            name='how_did_you_hear',
            field=models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('google_search', 'Google Search'), ('referral', 'Referral'), ('advertisement', 'Advertisement'), ('trade_show', 'Trade Show'), ('other', 'Other')], help_text='How did you hear about us', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artworkrequest',
            name='product_mockup',
            field=models.ImageField(blank=True, help_text='Product mockup image', null=True, upload_to='artwork_requests/'),
        ),
        migrations.AddField(
            model_name='artworkrequest',
            name='sports',
            field=models.JSONField(blank=True, default=list, help_text='List of sports (max 2)'),
        ),
    ]
