# Generated by Django 4.2.27 on 2026-01-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0018_artworkrequest_additional_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password to access this category', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in',
            field=models.CharField(blank=True, help_text='Section to show this category in', max_length=50, null=True),
        ),
    ]
