# Generated by Django 4.2.27 on 2026-01-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_management_app', '0019_category_password_category_show_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='password',
        ),
    ]
